 Favorite Snack

 a = my favorite Snack
 b = Melanie's favorite snack
 c = brownies
 d = plantain chips
 a = brownies
 b = plantain chips

 What to print for Tonyeli
favorite snack = brownies
 print a * 100
 'browiniesbrowiniesbrowiniesbrowiniesbrowiniesbrowiniesbrowiniesbrowiniesbrowiniesbrowiniesbrowiniesbrowiniesbrowiniesbrowiniesbrowiniesbrowiniesbrowiniesbrowiniesbrowiniesbrowiniesbrowiniesbrowiniesbrowiniesbrowiniesbrowiniesbrowiniesbrowiniesbrowiniesbrowiniesbrowiniesbrowiniesbrowiniesbrowiniesbrowiniesbrowiniesbrowiniesbrowiniesbrowiniesbrowiniesbrowiniesbrowiniesbrowiniesbrowiniesbrowiniesbrowiniesbrowiniesbrowiniesbrowiniesbrowiniesbrowiniesbrowiniesbrowiniesbrowiniesbrowiniesbrowiniesbrowiniesbrowiniesbrowiniesbrowiniesbrowiniesbrowiniesbrowiniesbrowiniesbrowiniesbrowiniesbrowiniesbrowiniesbrowiniesbrowiniesbrowiniesbrowiniesbrowiniesbrowiniesbrowiniesbrowiniesbrowiniesbrowiniesbrowiniesbrowiniesbrowiniesbrowiniesbrowiniesbrowiniesbrowiniesbrowiniesbrowiniesbrowiniesbrowiniesbrowiniesbrowiniesbrowiniesbrowiniesbrowiniesbrowiniesbrowiniesbrowiniesbrowiniesbrowiniesbrowiniesbrowinies'

Melanie's favorite snack
What to print for Melanie
favorite snack = plantain chips
print b * 100
'plantain chipsplantain chipsplantain chipsplantain chipsplantain chipsplantain chipsplantain chipsplantain chipsplantain chipsplantain chipsplantain chipsplantain chipsplantain chipsplantain chipsplantain chipsplantain chipsplantain chipsplantain chipsplantain chipsplantain chipsplantain chipsplantain chipsplantain chipsplantain chipsplantain chipsplantain chipsplantain chipsplantain chipsplantain chipsplantain chipsplantain chipsplantain chipsplantain chipsplantain chipsplantain chipsplantain chipsplantain chipsplantain chipsplantain chipsplantain chipsplantain chipsplantain chipsplantain chipsplantain chipsplantain chipsplantain chipsplantain chipsplantain chipsplantain chipsplantain chipsplantain chipsplantain chipsplantain chipsplantain chipsplantain chipsplantain chipsplantain chipsplantain chipsplantain chipsplantain chipsplantain chipsplantain chipsplantain chipsplantain chipsplantain chipsplantain chipsplantain chipsplantain chipsplantain chipsplantain chipsplantain chipsplantain chipsplantain chipsplantain chipsplantain chipsplantain chipsplantain chipsplantain chipsplantain chipsplantain chipsplantain chipsplantain chipsplantain chipsplantain chipsplantain chipsplantain chipsplantain chipsplantain chipsplantain chipsplantain chipsplantain chipsplantain chipsplantain chipsplantain chipsplantain chipsplantain chipsplantain chipsplantain chipsplantain chipsplantain chips'

5 Essential groceries

print (1,2,,3,4,5) = (fish, tomatoes, garlic, peppe, onion)
1. Fish 
2. Tomatoes
3. Garlic
4. Pepper
5. Onion

print each item seperately in order of item as indicated above



